### ISSUE TITLE
Some key controls are awkward to use with an AZERTY keyboard.

### ISSUE THREAD

**Issue by PoroCYon** [billgathen/pentaphone#1]
`W` and `;` (somehow `$` for me) are annoying to reach, and other keys should be possible, too.
In particular, `W` should be replaced with `Z` and `;`with `M` for AZERTY keyboards. These don't interfere with other keys, so it's possible to check for both all the time, without checking for the keyboard layout.

**Comment by jancborchardt** [comment]
Same for a German keyboard where `;` is `ö`. :)

**Comment by billgathen** [comment]
I'd love whatever info you can give me on the correct charCodes to use. Updating it would be straightforward, but I don't have easy access to those keyboard layouts.

I did run into a few different mappings between Chrome and Firefox, as you can see in https://github.com/billgathen/pentaphone/blob/master/src/js/stores/key_store.js with the double mappings for the semi-colon. That seems quite a problematic key! :smile: 

A pull request would be great, but if you can supply the numbers for each browser I can get them integrated.

Thanks for taking an interest in the Pentaphone!

**Comment by PoroCYon** [comment]
Key codes (for Belgian AZERTY (comma-variant)):
- `m`: 109
- `z`: 122
- `ö` seems to be 246, but it could differ from a German keyboard because it's a composite character.

**Comment by billgathen** [comment]
:+1:

**Comment by jancborchardt** [comment]
@billgathen ah, that’s where the codes are! I was looking around but ended up thinking they were hardcoded as the keyName in https://github.com/billgathen/pentaphone/blob/master/src/js/app.react.js

**Comment by jancborchardt** [comment]
Pull request at https://github.com/billgathen/pentaphone/pull/4, please review. :)
